import "./globals.css";

import { Crimson_Text } from "next/font/google";

const crimson = Crimson_Text({
  weight: "700",
  style: "italic",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Layout from "./components/Layout";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={crimson.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
